from tkinter import *
window = Tk()
window.title("Login App")
window.geometry("400x400")
frame = Frame(master= window, height= 300, width= 400, bg = "#d0efff")
lbl1 = Label(frame, text="Enter Name:", width= 12, bg= '#3895D3', fg="white")
lbl2 = Label(frame, text="Email-ID:", width= 12, bg='#3895D3', fg="white")
lbl3 = Label(frame, text="Enter Password", width= 12, bg= '#3895D3', fg="white")
name_entry = Entry(frame)
email_entry = Entry(frame)
pass_entry = Entry(frame, show='*')
def display():
    name = name_entry.get()
    greet = "Hey"  +name
    msg = "\nCongratulations on your new account"
    textbox.insert(END, greet)
    textbox.insert(END, msg)
textbox = Text(fg="black", bg="#BEBEBE")
btn = Button(text = "Create Account", command=display, bg="red")
frame.place(x=20, y=0)
lbl1.place(x=20, y=20)
name_entry.place(x=150, y=20)
lbl2.place(x=20, y=80)
email_entry.place(x=150, y=80)
lbl3.place(x=20, y=140)
pass_entry.place(x=150, y=140)
btn.place(x=130, y=210)
textbox.place(y=250)
window.mainloop()